/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Model.DoanhThu;
import Model.PC;
import Model.TBao;
import Model.ThucPham;
import Model.User;
import Service.Service;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author phien
 */
public class Order extends javax.swing.JFrame {

    /**
     * Creates new form Order
     */
    Service userService_46;
    User user_46;
    ThucPham tp_46;
    DefaultTableModel defaultTableModel_46;
    public Order() {
        initComponents();
        userService_46 = new Service();
        List<ThucPham> tps = userService_46.getAllTP();
        for (ThucPham tp:tps){
            jComboBox1_46.addItem(String.valueOf(tp.getTen()));
        }
    }
    public Order(User user){
        initComponents();
        this.user_46=user;
        userService_46 = new Service();
       jLabel1_46.setText("ID khách hàng: "+ user.getId()+" Tên KH: "+user.getTen());
        List<ThucPham> tps = userService_46.getAllTP();
        for (ThucPham tp:tps){
            jComboBox1_46.addItem(String.valueOf(tp.getTen()));
        }
        jComboBox2_46.removeAllItems();
        jComboBox2_46.addItem("Nhận tại quầy");
        List<PC> pcs = userService_46.getAllPC();
        for (PC pc:pcs){
            jComboBox2_46.addItem(pc.getIdPC());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1_46 = new javax.swing.JLabel();
        jComboBox1_46 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jSpinner1_46 = new javax.swing.JSpinner();
        jButton1_46 = new javax.swing.JButton();
        jComboBox2_46 = new javax.swing.JComboBox<>();
        jLabel2_46 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1_46.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel1_46.setText("jLabel1");
        getContentPane().add(jLabel1_46, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 340, 30));

        jComboBox1_46.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jComboBox1_46.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1_46ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1_46, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 320, 130, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 340, 210, 30));

        jSpinner1_46.setFont(new java.awt.Font("Segoe UI Black", 1, 20)); // NOI18N
        jSpinner1_46.setModel(new javax.swing.SpinnerNumberModel(1, null, null, 1));
        getContentPane().add(jSpinner1_46, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 340, -1, -1));

        jButton1_46.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jButton1_46.setText("Order");
        jButton1_46.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_46ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1_46, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 450, -1, -1));

        jComboBox2_46.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox2_46, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        jLabel2_46.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2_46.setText("Chọn nơi nhận");
        getContentPane().add(jLabel2_46, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Order.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, -4, 800, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1_46ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1_46ActionPerformed
        // TODO add your handling code here:
        ThucPham tp = new ThucPham();
        List<ThucPham> tps=userService_46.searchTP1(String.valueOf(jComboBox1_46.getSelectedItem()));
        for (ThucPham tp1:tps){
            jLabel2.setText(String.valueOf(tp1.getGia()+2000));
        }
    }//GEN-LAST:event_jComboBox1_46ActionPerformed

    private void jButton1_46ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_46ActionPerformed
        // TODO add your handling code here:
        DoanhThu dt= new DoanhThu();
        if (user_46.getTienNo()-Long.valueOf(jLabel2.getText())*Integer.valueOf(String.valueOf(jSpinner1_46.getValue()))<0)
        {
            JOptionPane.showMessageDialog(Order.this,"Khong du tien trong tai khoan","Loi",JOptionPane.ERROR_MESSAGE);
        }else{
        LocalDateTime current = LocalDateTime.now();
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
        String formatted = current.format(formatter);
        dt.setNgay(formatted);
        dt.setDoanhThu(Long.valueOf(jLabel2.getText())*Integer.valueOf(String.valueOf(jSpinner1_46.getValue())));
        dt.setGhiChu("Khach dat mua");
        user_46.setTienNo(user_46.getTienNo()-Long.valueOf(jLabel2.getText())*Integer.valueOf(String.valueOf(jSpinner1_46.getValue())));
        List<ThucPham> tp1 = userService_46.searchTP1(String.valueOf(jComboBox1_46.getSelectedItem()));
        ThucPham tp= tp1.get(0);
        tp.setSoLuong(tp.getSoLuong()-Integer.valueOf(String.valueOf(jSpinner1_46.getValue())));
        userService_46.updateTP(tp);
        userService_46.updateUser(user_46);
        userService_46.addDT(dt);
        
        TBao tb= new TBao();
        tb.setNd("ID khách đặt mua: "+user_46.getId()+"\nTên khách đặt mua: "+user_46.getTen()+"\nNhận tại: "+jComboBox2_46.getSelectedItem());
        userService_46.addTB(tb);
        
        this.dispose();
        }                  
    }//GEN-LAST:event_jButton1_46ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Order().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1_46;
    private javax.swing.JComboBox<String> jComboBox1_46;
    private javax.swing.JComboBox<String> jComboBox2_46;
    private javax.swing.JLabel jLabel1_46;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel2_46;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSpinner jSpinner1_46;
    // End of variables declaration//GEN-END:variables
}
